### ISSUE TITLE
Add usage instructions to readme on how to play the game.

### ISSUE THREAD

**Issue by Joearrowsmith** [Joearrowsmith/hackcambridge_2020#10]
I have struggled to start the server to show people, please can you guys write some usage instructions on the git repo.

**Comment by EdwardStables** [comment]
Pushed changes with README and some config changes to dev. Test it out and stick it in master if you're happy.

**Comment by Joearrowsmith** [comment]
What were the differences between master and dev? I thought master had the “broken” multiplayer but slightly less broken messaging system for agents.

**Comment by EdwardStables** [comment]
I don't know the state of master, I've never touched it. But the code previously in dev was definitely stable for human players. No branches have working connections for agents.

**Comment by Joearrowsmith** [comment]
Ok thanks! Have merged with master.
